name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.14
        architecture: x64
    - name: Build package
      run:  uv build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
